# Generated by Django 4.2.13 on 2024-07-09 15:57

import cloudinary.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Story',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, unique=True)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('body', models.TextField()),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('image', cloudinary.models.CloudinaryField(default='placeholder', max_length=255, verbose_name='image')),
                ('story_location', models.CharField(choices=[('Telford', 'Telford'), ('Shrewsbury', 'Shrewsbury'), ('Bishops Castle', 'Bishops Castle'), ('Bridgnorth', 'Bridgnorth'), ('Broseley', 'Broseley'), ('Church Stretton', 'Church Stretton'), ('Cleobury Mortimer', 'Cleobury Mortimer'), ('Clun', 'Clun'), ('Craven Arms', 'Craven Arms'), ('Ellesmere', 'Ellesmere'), ('Ludlow', 'Ludlow'), ('Market Drayton', 'Market Drayton'), ('Much Wenlock', 'Much Wenlock'), ('Newport', 'Newport'), ('Oswestry', 'Oswestry'), ('Shifnal', 'Shifnal'), ('Wem', 'Wem'), ('Whitchurch', 'Whitchurch'), ('Shropshire', 'Shropshire')], max_length=50)),
                ('news_category', models.CharField(choices=[('General', 'General'), ('Business', 'Business'), ('Charity', 'Charity'), ('Culture & Lifestyle', 'Culture & Lifestyle'), ('Education', 'Education'), ('Entertainment', 'Entertainment'), ('Family', 'Family'), ('Food', 'Food'), ('Ideas & Innovation', 'Ideas & Innovation'), ('Motoring', 'Motoring'), ('Nature', 'Nature'), ('Sport', 'Sport'), ('Travel', 'Travel')], max_length=50)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stories_story', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_on'],
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField()),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commenter', to=settings.AUTH_USER_MODEL)),
                ('story', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='stories.story')),
            ],
            options={
                'ordering': ['created_on'],
            },
        ),
    ]
