# Generated by Django 4.2.13 on 2024-07-11 21:41

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0004_alter_story_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='story',
            name='body',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
